import type { Knobs, Product, RuleRow } from "./types";

/**
 * Every number the screen shows lives here.
 * Change a value in the workshop and the same object is what the engine reads.
 */
export const R = {
  bufferFloor: 8_000,
  bufferOfIncome: 0.12,
  perDependent: 2_500,
  perUnemployedAdult: 4_000,
  metroFriction: 0.04,

  variableCounted: 0.5,
  spouseLenderShare: 0.65,
  spouseHouseShare: 0.9,
  itrOnlyForLender: true,
  cashLenderShareIfNoItr: 0.5,
  informalLenderShare: 0.4,
  gstBoostIfRegistered: 0.08,
  extraEarnCounted: 0.35,

  foirLender: {
    personalPrime: 0.48,
    personalStandard: 0.42,
    personalThin: 0.35,
    lap: 0.5,
    home: 0.5,
    gold: 0.5,
    twoWheeler: 0.45,
    business: 0.45,
  },
  foirHouse: {
    personalPrime: 0.36,
    personalStandard: 0.34,
    informal: 0.28,
    lap: 0.4,
    home: 0.4,
    gold: 0.35,
    twoWheeler: 0.32,
    business: 0.35,
  },

  consumptionHaircut: 0.15,
  consumptionMonthsCap: 8,
  emergencyOkMonths: 3,
  thinSavingsHaircut: 0.7,
  upcomingExpenseHaircut: 0.1,

  cardUtilFlag: 0.75,
  cardUtilBump: 0.75,
  bounceBump: 2.5,
  unknownBounceWiden: 0.75,
  highCostDebt: 24,
  mncGovtCut: 0.5,
  shortJobBump: 1.25,
  longStableCut: 0.25,
  youngBizBump: 1.25,
  personalFloor: 10.75,

  gst: 0.18,
  fee: {
    personal: 0.015,
    home: 0.005,
    lap: 0.01,
    gold: 0.01,
    two_wheeler: 0.02,
    business: 0.02,
  } as Record<Product, number>,

  ltv: {
    lapLow: 0.48,
    lapHigh: 0.58,
    homeLow: 0.75,
    homeHigh: 0.85,
    goldLow: 0.65,
    goldHigh: 0.75,
  },
  lapMinProperty: 5_00_000,
  lapCover: 1.5,
  twoWheelerCap: 2_50_000,
  minLoan: 20_000,
  personalCapMultipleHigh: 22,

  maxAgeUnsecured: 58,
  maxAgeSecured: 70,
  maxTenure: {
    personal: 60,
    home: 240,
    lap: 180,
    gold: 36,
    two_wheeler: 48,
    business: 84,
  } as Record<Product, number>,
  defaultTenure: {
    personal: 48,
    home: 180,
    lap: 108,
    gold: 24,
    two_wheeler: 36,
    business: 60,
  } as Record<Product, number>,

  stressIncomeDrop: 0.25,
  stressRateBump: 2.5,
  surplusFloor: 0.08,
  bounceNewEmiCap: 0.08,

  confidenceMust: 0.55,
  confidenceAdd: 0.45,
  unknownScoreCap: 0.56,
  unknownExpenseWiden: 0.12,
  bandWidenPerSkip: 0.1,
} as const;

export const RATE = {
  personal: {
    super: [10.75, 12.25],
    prime: [11.25, 13.5],
    good: [13.25, 16.5],
    fair: [16.5, 20.5],
    thin: [20.5, 27],
    unknownSalaried: [13, 20.5],
    unknownSelf: [15.5, 22.5],
    unknownInformal: [18.5, 28],
  },
  lap: {
    super: [9.75, 11.25],
    prime: [10.1, 12.1],
    good: [10.6, 13],
    fair: [11.75, 14.5],
    thin: [13.25, 16.5],
    unknown: [10.75, 14],
  },
  home: {
    super: [8.15, 8.85],
    prime: [8.3, 9.2],
    good: [8.7, 9.7],
    fair: [9.2, 10.4],
    thin: [10.1, 11.75],
    unknown: [8.6, 10.2],
  },
  gold: [9.75, 14.25],
  twoWheeler: {
    prime: [11.25, 14.75],
    standard: [13.25, 17.5],
    informal: [15.5, 21],
    unknown: [13.5, 19],
  },
  business: {
    documented: [13.75, 18],
    thin: [16.25, 22.5],
    unknown: [16, 22],
  },
} as const;

export const MULTIPLE = {
  personal: {
    super: [16, 22],
    prime: [14, 20],
    good: [10, 16],
    fair: [7, 12],
    thin: [3, 7],
    unknownSalaried: [8, 16],
    unknownSelf: [5, 11],
    unknownInformal: [3, 7],
  },
  business: { documented: [10, 20], thin: [5, 10] },
  lap: [20, 42],
  home: [24, 48],
} as const;

export function defaultKnobs(): Knobs {
  return {
    householdFoirPersonal: R.foirHouse.personalPrime,
    householdFoirInformal: R.foirHouse.informal,
    consumptionHaircut: R.consumptionHaircut,
    lapLtvLow: R.ltv.lapLow,
    lapLtvHigh: R.ltv.lapHigh,
    bounceRateBump: R.bounceBump,
    highCostDebt: R.highCostDebt,
    stressIncomeDrop: R.stressIncomeDrop,
    stressRateBump: R.stressRateBump,
  };
}

export function feeAllIn(product: Product): number {
  return R.fee[product] * (1 + R.gst);
}

export const CATALOG: RuleRow[] = [
  {
    id: "two_books",
    what: "Two amount books",
    value: "Lender book vs household book",
    why: "A branch underwrites documents and a grid. A family underwrites rent, school, and a slow month. Those two numbers are supposed to disagree.",
    source: "My judgement — this is the product",
  },
  {
    id: "foir_lender_pl_prime",
    what: "Lender FOIR — prime personal loan",
    value: "48%",
    why: "Private-bank unsecured grids for 750+ salaried files often sit near half of net. I sit one notch under the 50% folklore so I do not flit a sanction the branch will not print.",
    source: "My judgement. No statute publishes FOIR",
  },
  {
    id: "foir_house_pl_prime",
    what: "Household FOIR — prime personal loan",
    value: "36%",
    why: "The extra 12 points on the sanction letter is how a Bengaluru rent + car EMI becomes 65% of pay. The borrower should walk in with the tighter number.",
    source: "My judgement",
  },
  {
    id: "foir_informal",
    what: "Household FOIR — informal income",
    value: "28%",
    why: "A rider's week can vanish. A 36% FOIR that an MNC salary can service will bounce on a rain week in Hubballi.",
    source: "My judgement",
  },
  {
    id: "foir_lap",
    what: "Lender FOIR — shop-secured LAP",
    value: "50% lender / 40% household",
    why: "The shop is a second way out, so the grid loosens. The kitchen still has to pay the EMI if custom is slow.",
    source: "My judgement, typical NBFC LAP practice",
  },
  {
    id: "residual",
    what: "Residual buffer",
    value: "₹8,000 floor, or 12% of household income, plus ₹2,500 per dependent and ₹4,000 per unemployed adult",
    why: "FOIR alone pretends expenses do not exist. I also leave cash on the table that cannot become EMI.",
    source: "My judgement — rupee floors beat pure percentages for thin files",
  },
  {
    id: "metro",
    what: "Metro friction",
    value: "+4% of income added to the buffer",
    why: "Bengaluru rent is not Mysuru rent. If they already typed expenses I do not double-count; this only bites when we must guess a living cost.",
    source: "My judgement",
  },
  {
    id: "unknown_score",
    what: "Unknown credit score",
    value: "A wide band. Never 300.",
    why: "No file is not a defaulted file. Pricing a blank as 300 invents a stain and then 'tightens' a rate we have no right to tighten.",
    source: "My judgement",
  },
  {
    id: "unknown_savings",
    what: "Emergency savings unanswered",
    value: "Do not haircut the midpoint. Widen the low end.",
    why: "Silence is not an empty FD. Treating 'I skipped' as 'I have nothing' would pretend we know they are fragile.",
    source: "My judgement — unknown is never zero",
  },
  {
    id: "variable",
    what: "Variable pay counted",
    value: "50% of the variable slice. Unanswered = 0 extra, band widened.",
    why: "Bonus is real until the year it is not. I will not invent a 10% variable mix on a clean CTC.",
    source: "My judgement",
  },
  {
    id: "itr",
    what: "Self-employed lender income",
    value: "ITR ÷ 12. Cash till is ignored on the lender book.",
    why: "A branch underwrites the return, not the drawer. Household book uses the low month of cash, because that is the month the EMI still arrives.",
    source: "My judgement",
  },
  {
    id: "no_itr",
    what: "Self-employed, no ITR",
    value: "Lender counts 50% of typical cash",
    why: "Undocumented cash is not bankable rupee-for-rupee.",
    source: "My judgement",
  },
  {
    id: "informal_income",
    what: "Informal lender income",
    value: "40% of typical stated month",
    why: "Platform payouts plus cash tailoring rarely survive a credit spreadsheet at face value.",
    source: "My judgement",
  },
  {
    id: "spouse",
    what: "Spouse / co-applicant income",
    value: "65% lender if not formally added, 90% household. 100% lender if they say co-applicant.",
    why: "Most grids haircut the second income. The house can plan on more of it than the banker will.",
    source: "My judgement",
  },
  {
    id: "gst",
    what: "GST-registered shop",
    value: "+8% on lender-recognised income",
    why: "A GST file is easier to underwrite than a pure cash kirana. It is a small lift, not a rewrite of the ITR.",
    source: "My judgement",
  },
  {
    id: "ltv_lap",
    what: "LTV on shop / commercial",
    value: "48–58%",
    why: "A Mysuru shop is not a Mumbai flat. RBI home-loan LTV caps do not apply to a kirana premises. I sit under typical 60% LAP talk.",
    source: "My judgement. Home LTV is [5] in RULES.md; this is not a home",
  },
  {
    id: "ltv_gold",
    what: "LTV on gold",
    value: "65–75%",
    why: "I stay at or under the 75% bank gold-loan ceiling.",
    source: "RBI gold-loan LTV 75% — RULES.md [3]",
  },
  {
    id: "wedding",
    what: "Consumption (wedding / lifestyle) haircut",
    value: "15% off household EMI room, and principal capped at 8× monthly take-home",
    why: "A wedding does not earn. Financing more than eight months of pay with years of interest is a party the lender enjoys more than the family.",
    source: "My judgement",
  },
  {
    id: "thin_savings",
    what: "Emergency savings under 3 months",
    value: "Household EMI room × 0.70",
    why: "The first shock becomes a second loan. Only when they tell me savings are thin — I do not assume this from a skip.",
    source: "My judgement",
  },
  {
    id: "earn",
    what: "Stated extra monthly earn from the loan",
    value: "35% counted, on the household book only",
    why: "Everyone over-forecasts the second stock line. I believe about a third. I do not let optimism raise the lender book.",
    source: "My judgement",
  },
  {
    id: "bounce",
    what: "Bounce in the last 12 months",
    value: "+2.5pp on rate, lender ticket ×0.45–0.7, new EMI capped at 8% of household income",
    why: "The file is already talking. Adding another EMI is how late becomes default.",
    source: "My judgement",
  },
  {
    id: "high_cost",
    what: "Don't-borrow fire — bounce + existing rate",
    value: "Bounce AND existing rate ≥ 24%",
    why: "App / payday paper at 30% is the fire. A new scooter is more fuel. Refinance or stop. A bounce alone is not an automatic don't if the rest of the file is clean.",
    source: "My judgement",
  },
  {
    id: "mnc",
    what: "MNC / government employer",
    value: "−0.50pp on the band",
    why: "These files are priced better. I do not pretend they get a home-loan rate on unsecured paper — personal-loan floor is 10.75%.",
    source: "My judgement",
  },
  {
    id: "job_short",
    what: "Job under 12 months",
    value: "+1.25pp",
    why: "Flight risk. The grid has seen this movie.",
    source: "My judgement",
  },
  {
    id: "stable",
    what: "Job ≥ 5 years or business ≥ 10 years",
    value: "−0.25pp",
    why: "Vintage is a small notch, not a new product.",
    source: "My judgement",
  },
  {
    id: "young_biz",
    what: "Business under 3 years",
    value: "+1.25pp",
    why: "For a self-employed file, vintage is the bureau.",
    source: "My judgement",
  },
  {
    id: "card",
    what: "Card utilisation ≥ 75%",
    value: "+0.75pp on the high end only",
    why: "High utilisation is a surcharge even with a decent score. I do not move the low end — a good score can still print a decent offer.",
    source: "My judgement",
  },
  {
    id: "apr",
    what: "All-in APR",
    value: "Processing fee + 18% GST, IRR on net disbursal",
    why: "A 12% sticker with a 2% fee is not 12%. This follows the spirit of RBI Key Facts Statement disclosure, not a legal opinion.",
    source: "RBI KFS [1]; GST 18% on banking services [2]",
  },
  {
    id: "fee",
    what: "Fee used before GST",
    value: "Personal 1.5%, home 0.5%, LAP 1%, gold 1%, two-wheeler 2%, business 2%",
    why: "Advertised fees move. These are walk-in typicals, not a live tariff.",
    source: "My judgement, anchored to advertised pages in RULES.md [4]",
  },
  {
    id: "stress",
    what: "Stress case",
    value: "Income −25% or rate +250 bps — worse FOIR wins",
    why: "Informal and bonus-linked pay already move more than 20%. Reset cycles happen. If the ticket fails stress, I still show the normal-month ceiling, and I say the ticket is fragile.",
    source: "My judgement",
  },
  {
    id: "age",
    what: "Max age at maturity",
    value: "58 unsecured / 70 secured",
    why: "Unsecured grids usually stop before retirement. Secured can run against the asset.",
    source: "Typical Indian grids + my judgement",
  },
  {
    id: "tenure",
    what: "Default tenure used for the recommended ticket",
    value: "Personal 48m, LAP 108m, two-wheeler 36m, gold 24m, business 60m, home 180m",
    why: "Longer tenure makes a dangerous ticket look cheap. I quote a middle tenor, then show the trade-off.",
    source: "My judgement",
  },
  {
    id: "tw_cap",
    what: "Two-wheeler ticket cap",
    value: "₹2,50,000",
    why: "An e-scooter is not a car loan. Counters still try.",
    source: "My judgement",
  },
  {
    id: "min",
    what: "Smallest ticket I will print",
    value: "₹20,000",
    why: "Below this I print zero rather than a toy loan.",
    source: "My judgement",
  },
  {
    id: "anita_counter",
    what: "Unsafe two-wheeler sales pitch on a 'don't' file",
    value: "Show ₹70,000–₹1,20,000 as what the counter may still try to book, household ₹0",
    why: "A prudent FOIR after app EMIs is ~₹0. Hiding the sales pitch would leave her unarmed tomorrow.",
    source: "My judgement",
  },
  {
    id: "rates",
    what: "Headline rate bands 2026",
    value: "See RATE tables in constants.ts",
    why: "Not a live market feed. Anchored to advertised retail pages I could open, then widened for thin files.",
    source: "Anchored to [4][6][7] in RULES.md, then my judgement",
  },
];
